# your informations
author:
  name: RYimeng
  description:
  picture: /assets/images/avatar.jpg
  favicon: /assets/images/favicon.png

# site description
description: Thoughts and writings about software engineering by Bernardo Pacheco.

# site url
url: http://bernardopacheco.net

# site title
title: RYimeng

# site version
version: 1.0.1

# number of posts per page
paginate: 10

# your github username
github_username: MelodyRen1998

# set true to include or false to exclude share option
share:
  twitter: false
  facebook: false
  google_plus: false
  linkedin: false
  disqus: false

# if share.facebook is true, provide your facebook app id
# facebook_app_id: 730635297031262

# if share.disqus is true, provide your disqus shortname, the api key and the number of comments to display
# disqus_username: bernardopacheco
# disqus_api_key: o2szu05bLNqiXiRvqe2oFvIHYYVR24eVkQiGs5WHcj0VUnvF8GCqD9HQUZErwCe7
# disqus_recent_comments_to_display: 5

# google analytics ID
# google_analytics_id: UA-58186085-1

markdown: kramdown
highlighter: rouge
exclude: [ 'README.md', 'src/', 'node_modules', 'package.json', 'Gruntfile.js' ]
excerpt_separator: <!--excerpt_separator-->

# Gems
gems: [jekyll-paginate]
